version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - ./project:/usr/share/nginx/html
    ports:
      - "8080:80"
    environment:
      VIRTUAL_PORT: 80

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  docker-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - ./project:/usr/share/nginx/html
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
    volumes_from:
      - nginx
    depends_on:
      - nginx
      - nginx-proxy
